version: '3.3'

services:
   mysql:
     container_name: MySQL
     image: luukert/bp2:db_1
     volumes:
       - db_data:/var/lib/mysql
     restart: always

   wordpress:
     container_name: Wordpress
     depends_on:
       - mysql
     image: luukert/bp2:wordpress_1
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: mysql:3306

volumes:
    db_data: {}


